services:
  dynamodb-local:
    command: '-jar DynamoDBLocal.jar -sharedDb -dbPath ./data'
    image: 'amazon/dynamodb-local:latest'
    container_name: dynamodb-local
    ports:
      - '8000:8000'
    volumes:
      - './docker/dynamodb:/home/dynamodblocal/data'
    working_dir: /home/dynamodblocal

  zookeeper:
    image: 'confluentinc/cp-zookeeper:latest'
    environment:
      - 'ZOOKEEPER_CLIENT_PORT=2181'
      - 'ZOOKEEPER_TICK_TIME=2000'
    ports:
      - '22181:2181'

  kafka:
    image: 'wurstmeister/kafka:latest'
    depends_on:
      - zookeeper
    ports:
      - '9092:9092'
      - '59092:59092'
    environment:
      - 'KAFKA_BROKER_ID=1'
      - 'KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181'
      - 'KAFKA_LISTENERS=PLAINTEXT://kafka:59092,PLAINTEXT_HOST://kafka:9092'
      - 'KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:59092,PLAINTEXT_HOST://localhost:9092'
      - 'KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      - 'KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT'
      - 'KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1'
      - 'KAFKA_CREATE_TOPICS=transaction-requests:2:1'

  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    depends_on:
      - kafka
      - zookeeper
    ports:
      - "8282:8080"
    restart: always
    environment:
      - KAFKA_CLUSTERS_0_NAME=local-kafka
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:59092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:22181
